server:
  port: 8040
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

spring:
  application:
    name: blog-web-01
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    time-zone: GMT-8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    property-naming-strategy: SNAKE_CASE

ribbon:
  ReadTimeout: 5000 # 请求连接的超时时间
  ConnectionTimeout: 10000 # 请求处理的超时时间

## open feign authconfig
feign:
  client:
    config:
      default:
        loggerLevel: full
  httpclient:
    enabled: true # 支持 httpclient 的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数

## logging 相关
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug