server:
  port: 8030
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

spring:
  application:
    name: blog-admin-01
  profiles:
    active: test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    time-zone: GMT-8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
#  cloud:
#    nacos:
#      discovery:
#        server-addr: http://192.168.88.100:8848
#        username: nacos
#        password: nacos
#        enabled: true
#        group: DEFAULT_GROUP
#        register-enabled: true
