spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://localhost:3306/permission?useUnicode=true&characterEncoding-utr-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  cloud:
    ## nacos authconfig
    nacos:
      discovery:
        server-addr: http://192.168.88.100:8848
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
        service: ${spring.application.name}
        register-enabled: true
      config:
        group: DEFAULT_GROUP
        share-data-ids: ${spring.application.name}-${spring.profiles.active}
        server-addr: http://192.168.88.100:8848
        namespace: public
    ## gateway authconfig
    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedHeaders: "*"
#            allowCredentials: true
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
      # 设置与服务注册发现组件结合, 这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      # 配置路由规则
      routes:
        ## 需要路由到的 server name
        - id: blog-admin
          # 采用 LoadBalanceClient 方式请求, 以 lb:// 开头, 后面的是注册在 Nacos 上的服务名
          uri: lb://blog-admin-01
          # Predicate 翻译过来是"谓词"的意思，必须配置这个属性，主要作用是匹配用户的请求，有很多种用法
          predicates:
            - Path=/blog-admin/**
          filters:
            ## 前缀过滤，默认配置下，我们的请求路径是 http://localhost:8888/business-oauth2/** 这时会路由到指定的服务
            ## 此处配置去掉 1 个路径前缀，再配置上面的 Path=/restapis/**，就能按照 http://localhost:8888/api/** 的方式访问了
            ## 将 /blog-admin/**  重写为/**, 将第一个路径去掉(去掉blog-admin)
            - StripPrefix=1
        - id: blog-web
          uri: lb://blog-web-01
          predicates:
            - Path=/blog-web/**
          filters:
            - StripPrefix=1
        - id: security-server
          uri: lb://security-server-01
          predicates:
            - Path=/admin-login/**
          filters:
            - StripPrefix=1
  config:
    import: nacos:application-dev.yml

## 配置需要skip的path
gateway-config:
  url:
    skip-urls:
      - /blog-admin/admin/**
      - /admin-login/admin/**

## gateway endpoint
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

## logging 相关
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug